//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YALV.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YALV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string About_AboutGroupBox_Header {
            get {
                return ResourceManager.GetString("About_AboutGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
        /// </summary>
        public static string About_CreditsGroupBox_Header {
            get {
                return ResourceManager.GetString("About_CreditsGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YALV! is a log viewer for Log4Net that allows to compare multiple log files simultaneously.
        ///
        ///MAIN FEATURES:
        ///- Log files merging
        ///- Dynamic filtering
        ///- Dynamic show/hide log levels
        ///- Save favorite log folders
        ///- Open most recently used files
        ///- Column sorting
        ///
        ///Log4Net config file must be setup with XmlLayoutSchemaLog4j layout; just need a few lines in your application config file to configure it to use this format (see examples on right).
        ///
        ///It is a WPF Application based on .NET Framework 4.0 and written with C#  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YALV! - Yet Another Log4Net Viewer ähnelt.
        /// </summary>
        public static string About_Header_Text {
            get {
                return ResourceManager.GetString("About_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log4Net Configuration ähnelt.
        /// </summary>
        public static string About_Log4NetConfigurationGroupbox_Header {
            get {
                return ResourceManager.GetString("About_Log4NetConfigurationGroupbox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample 1: ähnelt.
        /// </summary>
        public static string About_Log4NetConfigurationGroupbox_Sample1_Title {
            get {
                return ResourceManager.GetString("About_Log4NetConfigurationGroupbox_Sample1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample 2: ähnelt.
        /// </summary>
        public static string About_Log4NetConfigurationGroupbox_Sample2_Title {
            get {
                return ResourceManager.GetString("About_Log4NetConfigurationGroupbox_Sample2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YALV! - About ähnelt.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0} ähnelt.
        /// </summary>
        public static string About_Version_Text {
            get {
                return ResourceManager.GetString("About_Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string AddFolderPath_Grid_NameColumn_Name {
            get {
                return ResourceManager.GetString("AddFolderPath_Grid_NameColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        public static string AddFolderPath_Grid_PathColumn_Name {
            get {
                return ResourceManager.GetString("AddFolderPath_Grid_PathColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folders list saved! ähnelt.
        /// </summary>
        public static string AddFolderPathVM_commandSaveExecute_SuccessMessage {
            get {
                return ResourceManager.GetString("AddFolderPathVM_commandSaveExecute_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success ähnelt.
        /// </summary>
        public static string AddFolderPathVM_commandSaveExecute_SuccessTitle {
            get {
                return ResourceManager.GetString("AddFolderPathVM_commandSaveExecute_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading... ähnelt.
        /// </summary>
        public static string CircularProgressBar_CircularProgressBar_BusyText {
            get {
                return ResourceManager.GetString("CircularProgressBar_CircularProgressBar_BusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add folder to Favorites ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_AddNewItem_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_AddNewItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_Exit_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_Exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove folder from Favorites ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_RemoveSelectedItem_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_RemoveSelectedItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Favorites ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_SaveList_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_SaveList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ADD ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_AddNewItem_Text {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_AddNewItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Folder to Favorites ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_AddNewItem_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_AddNewItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die REMOVE ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_RemoveSelectedItem_Text {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_RemoveSelectedItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Selected Folder from Favorites ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_RemoveSelectedItem_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_RemoveSelectedItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SAVE ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_SaveList_Text {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_SaveList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Favorites ähnelt.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_SaveList_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_SaveList_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_AboutMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_AboutMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add File... ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_AddFile_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_AddFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Folder to Favorites... ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_AddFolderPath_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_AddFolderPath_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_Exit_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_Exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open File... ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_OpenFile_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_OpenFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent Files ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_RecentFiles_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_RecentFiles_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Folder... ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_SelectFolder_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_SelectFolder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Filters ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_ClearFilters_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_ClearFilters_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete File ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_DeleteFile_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_DeleteFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open containing Folder in Explorer ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_OpenSelectedFolder_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_OpenSelectedFolder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh File List ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_RefreshFileList_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_RefreshFileList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh Log ähnelt.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_RefreshLog_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_RefreshLog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ADD FILE ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_AddFile_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add File... ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_AddFile_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFile_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ADD FOLDER ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_AddFolderPath_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFolderPath_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Folder to Favorites... ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_AddFolderPath_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFolderPath_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CLEAR FILTERS ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_ClearFilters_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_ClearFilters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Filters ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_ClearFilters_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_ClearFilters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DELETE FILE ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_DeleteSelectedFile_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_DeleteSelectedFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete selected file ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_DeleteSelectedFile_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_DeleteSelectedFile_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OPEN FILE ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_OpenFile_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_OpenFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open File... ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_OpenFile_ToolTip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_OpenFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die REFRESH ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_RefreshLog_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_RefreshLog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh Log ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_RefreshLog_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_RefreshLog_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OPEN FOLDER ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_SelectFolder_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_SelectFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Folder... ähnelt.
        /// </summary>
        public static string Common_Components_MainToolbar_SelectFolder_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_SelectFolder_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en ähnelt.
        /// </summary>
        public static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter {0} ähnelt.
        /// </summary>
        public static string FilteredGridManager_BuildDataGrid_FilterTextBox_Tooltip {
            get {
                return ResourceManager.GetString("FilteredGridManager_BuildDataGrid_FilterTextBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MMM d, HH:mm:ss.fff ähnelt.
        /// </summary>
        public static string GlobalHelper_DISPLAY_DATETIME_FORMAT {
            get {
                return ResourceManager.GetString("GlobalHelper_DISPLAY_DATETIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -{0} s ähnelt.
        /// </summary>
        public static string GlobalHelper_getTimeDelta_Negative_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_getTimeDelta_Negative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die +{0} s ähnelt.
        /// </summary>
        public static string GlobalHelper_getTimeDelta_Positive_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_getTimeDelta_Positive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error reading Favorites file!
        ///[{0}]
        ///
        ///{1} ähnelt.
        /// </summary>
        public static string GlobalHelper_ParseFolderFile_Error_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseFolderFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string GlobalHelper_ParseFolderFile_Error_Title {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseFolderFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error reading log file!
        ///[{0}]
        ///
        ///{1} ähnelt.
        /// </summary>
        public static string GlobalHelper_ParseLogFile_Error_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseLogFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string GlobalHelper_ParseLogFile_Error_Title {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseLogFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error saving Favorites file!
        ///[{0}]
        ///
        ///{1} ähnelt.
        /// </summary>
        public static string GlobalHelper_SaveFolderFile_Error_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_SaveFolderFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string GlobalHelper_SaveFolderFile_Error_Title {
            get {
                return ResourceManager.GetString("GlobalHelper_SaveFolderFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Refresh ähnelt.
        /// </summary>
        public static string MainWindow_AutoRefresh_Checkbox_Text {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_Checkbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease Interval ähnelt.
        /// </summary>
        public static string MainWindow_AutoRefresh_DecreaseInterval_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_DecreaseInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase Interval ähnelt.
        /// </summary>
        public static string MainWindow_AutoRefresh_IncreaseInterval_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_IncreaseInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh Interval ähnelt.
        /// </summary>
        public static string MainWindow_AutoRefresh_RefreshInterval_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_RefreshInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_Application_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Application_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_Class_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Class_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_File_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host Name: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_HostName_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_HostName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Item Id: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_ItemId_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_ItemId_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_Level_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Level_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_Line_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Line_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Machine Name: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_MachineName_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_MachineName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_Message_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Method: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_Method_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Method_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_Number_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Number_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thread: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_Thread_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Thread_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Throwable: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_Throwable_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Throwable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Δ [time diff with previous log entry]: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_TimeDiff_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_TimeDiff_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Stamp: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_TimeStamp_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_TimeStamp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Name: ähnelt.
        /// </summary>
        public static string MainWindow_DetailsBox_UserName_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_UserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete File ähnelt.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_DeleteFile_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_DeleteFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Selected Folder ähnelt.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_OpenSelectedFolder_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_OpenSelectedFolder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh File List ähnelt.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_RefreshFileList_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_RefreshFileList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All Files ähnelt.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_SelectAll_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_SelectAll_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear All Files ähnelt.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_SelectNone_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_SelectNone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dddd, MMMM d, yyyy h:mm:ss.fff tt ähnelt.
        /// </summary>
        public static string MainWindow_FullDateTimeFormatWithMilliseconds {
            get {
                return ResourceManager.GetString("MainWindow_FullDateTimeFormatWithMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy To Clipboard ähnelt.
        /// </summary>
        public static string MainWindow_GridContextMenu_CopyToClipboard {
            get {
                return ResourceManager.GetString("MainWindow_GridContextMenu_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select File To Merge ähnelt.
        /// </summary>
        public static string MainWindow_MergeFile_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_MergeFile_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECTION ähnelt.
        /// </summary>
        public static string MainWindow_SelectionGroupBox_Header {
            get {
                return ResourceManager.GetString("MainWindow_SelectionGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die filtered items count / full items count ähnelt.
        /// </summary>
        public static string MainWindow_SelectionTooltip {
            get {
                return ResourceManager.GetString("MainWindow_SelectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SHOW/HIDE ähnelt.
        /// </summary>
        public static string MainWindow_ShowHideGroupBox_Header {
            get {
                return ResourceManager.GetString("MainWindow_ShowHideGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YALV! - Yet Another Log4Net Viewer ähnelt.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} s ähnelt.
        /// </summary>
        public static string MainWindowVM_AutoRefreshIntervalLocalized_Format {
            get {
                return ResourceManager.GetString("MainWindowVM_AutoRefreshIntervalLocalized_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unreadable File!
        ///
        ///{0} ähnelt.
        /// </summary>
        public static string MainWindowVM_bkLoaderCompleted_UnreadableFile_Text {
            get {
                return ResourceManager.GetString("MainWindowVM_bkLoaderCompleted_UnreadableFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string MainWindowVM_bkLoaderCompleted_UnreadableFile_Title {
            get {
                return ResourceManager.GetString("MainWindowVM_bkLoaderCompleted_UnreadableFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete all checked files? ähnelt.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmText {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Delete ähnelt.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmTitle {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete all selected files? ähnelt.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmText {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Delete ähnelt.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmTitle {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Log File ähnelt.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_Add_Log_File {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_Add_Log_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All files ähnelt.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_AllFilesCaption {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_AllFilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Log File ähnelt.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_Open_Log_File {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_Open_Log_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Xml files ähnelt.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_XmlFilesCaption {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_XmlFilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Log Folder ähnelt.
        /// </summary>
        public static string MainWindowVM_commandSelectFolderExecute_Description {
            get {
                return ResourceManager.GetString("MainWindowVM_commandSelectFolderExecute_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error deleting file!
        ///[{0}]
        ///
        ///{1} ähnelt.
        /// </summary>
        public static string MainWindowVM_deleteFile_ErrorMessage_Text {
            get {
                return ResourceManager.GetString("MainWindowVM_deleteFile_ErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string MainWindowVM_deleteFile_ErrorMessage_Title {
            get {
                return ResourceManager.GetString("MainWindowVM_deleteFile_ErrorMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_AppColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_AppColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_ClassColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_ClassColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HostName ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_HostNameColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_HostNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Id ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_IdColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_IdColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_LevelColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_LevelColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Machine Name ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_MachineNameColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_MachineNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_MessageColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_MessageColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Method ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_MethodColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_MethodColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logger ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_NumberColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_NumberColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thread ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_ThreadColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_ThreadColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timestamp ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_TimeStampColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_TimeStampColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Name ähnelt.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_UserNameColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_UserNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory not found!
        ///[{0}] ähnelt.
        /// </summary>
        public static string MainWindowVM_loadFolderFiles_ErrorMessage_Text {
            get {
                return ResourceManager.GetString("MainWindowVM_loadFolderFiles_ErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string MainWindowVM_loadFolderFiles_ErrorMessageText_Title {
            get {
                return ResourceManager.GetString("MainWindowVM_loadFolderFiles_ErrorMessageText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent ähnelt.
        /// </summary>
        public static string MainWindowVM_updateJumpList_CustomCategoryName {
            get {
                return ResourceManager.GetString("MainWindowVM_updateJumpList_CustomCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YALV! - Edit Favorites ähnelt.
        /// </summary>
        public static string SaveFolderPath_Title {
            get {
                return ResourceManager.GetString("SaveFolderPath_Title", resourceCulture);
            }
        }
    }
}
